name: Check Movie Dates

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          API_URL: ${{ vars.API_URL }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          CGV_SECRET_KEY: ${{ vars.CGV_SECRET_KEY }}
        run: python main.py

      - name: Commit seen_dates.json to `seen-dates` branch with timestamp
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          TIMESTAMP=$(TZ=Asia/Seoul date "+%Y-%m-%d %H:%M:%S %Z")
          TEMP_BRANCH=gh-actions-temp

          git fetch origin seen-dates:seen-dates || git switch -c seen-dates
          git checkout -b $TEMP_BRANCH origin/seen-dates || git checkout -b $TEMP_BRANCH

          cp seen_dates.json .

          if [[ `git status --porcelain seen_dates.json` ]]; then
            git add seen_dates.json
            git commit -m "chore(seen-dates): update seen_dates.json [auto] - $TIMESTAMP"
            git push origin $TEMP_BRANCH:seen-dates
          else
            echo "No changes to seen_dates.json"
          fi